export EDITOR="lvim"
export SUDO_EDITOR="lvim"
export BUN_INSTALL="$HOME/.bun"
export PATH="$PATH:$HOME/bin:$HOME/.cargo/bin:$HOME/.local/bin:$HOME/.scripts/bin:$HOME/.ghcup/bin:$HOME/.deno/bin:$BUN_INSTALL/bin:$HOME/.nix-profile/bin"
export DENO_INSTALL="$HOME/.deno"
export SSH_ASKPASS="/usr/bin/ksshaskpass"
export GIT_ASKPASS="/usr/bin/ksshaskpass"
export SSH_ASKPASS_REQUIRE="prefer"

alias svim="sudoedit"
alias vim="lvim-wrapper.sh"
